'use client'

import { useState, useEffect } from 'react'
import { Plus, Trash2, Edit2, Mail, X, Code2, Copy, Check } from 'lucide-react'
import toast from 'react-hot-toast'
import {
  listEmailTemplates,
  createEmailTemplate,
  updateEmailTemplate,
  deleteEmailTemplate,
  type EmailTemplate,
  type EmailTemplateType,
  type CreateEmailTemplatePayload,
} from '@/lib/api/email-templates'

const TYPE_LABELS: Record<EmailTemplateType, string> = {
  BUILTIN: 'Built-in',
  CUSTOM_HTML: 'Custom HTML',
  SENDGRID: 'SendGrid',
  MAILCHIMP: 'Mailchimp',
  BREVO: 'Brevo',
}

const TYPE_COLORS: Record<EmailTemplateType, string> = {
  BUILTIN: 'bg-blue-100 text-blue-700',
  CUSTOM_HTML: 'bg-purple-100 text-purple-700',
  SENDGRID: 'bg-green-100 text-green-700',
  MAILCHIMP: 'bg-yellow-100 text-yellow-700',
  BREVO: 'bg-orange-100 text-orange-700',
}

const STARTER_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Email</title>
  <style>
    body { margin: 0; padding: 0; background: #f4f4f5; font-family: Arial, sans-serif; }
    .wrapper { max-width: 600px; margin: 32px auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }
    .header { background: #1e293b; padding: 24px 32px; }
    .header h1 { margin: 0; color: #ffffff; font-size: 20px; }
    .content { padding: 32px; color: #374151; font-size: 15px; line-height: 1.6; }
    .footer { background: #f8fafc; padding: 16px 32px; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>Your Company</h1>
    </div>
    <div class="content">
      {{ body }}
    </div>
    <div class="footer">
      You received this email from Your Company &middot; Unsubscribe
    </div>
  </div>
</body>
</html>`

const VARIABLES_REFERENCE = [
  { variable: '{{ body }}', desc: 'Required — the email body generated by the agent is injected here.' },
  { variable: '{{ content }}', desc: 'Alias for {{ body }}. Either can be used.' },
]

const THIRD_PARTY_VARS: Record<string, { variable: string; desc: string }[]> = {
  SENDGRID: [
    { variable: '{{subject}}', desc: 'Email subject (SendGrid substitution tag)' },
    { variable: '{{first_name}}', desc: 'Recipient first name if passed via dynamic data' },
  ],
  MAILCHIMP: [
    { variable: '*|FNAME|*', desc: 'Recipient first name (Mailchimp merge tag)' },
    { variable: '*|EMAIL|*', desc: 'Recipient email address' },
  ],
  BREVO: [
    { variable: '{{params.name}}', desc: 'Custom param passed at send time' },
    { variable: '{{contact.EMAIL}}', desc: 'Recipient email from Brevo contact' },
  ],
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500) }}
      className="ml-1 inline-flex items-center text-gray-400 hover:text-gray-600"
      title="Copy"
    >
      {copied ? <Check size={12} className="text-green-500" /> : <Copy size={12} />}
    </button>
  )
}

function TemplateModal({
  editTarget, form, setForm, saving, onSave, onClose,
}: {
  editTarget: EmailTemplate | null
  form: CreateEmailTemplatePayload
  setForm: React.Dispatch<React.SetStateAction<CreateEmailTemplatePayload>>
  saving: boolean
  onSave: () => void
  onClose: () => void
}) {
  const isThirdParty = ['SENDGRID', 'MAILCHIMP', 'BREVO'].includes(form.template_type)
  const isCustom = form.template_type === 'CUSTOM_HTML'
  const modalWidth = isCustom ? 'max-w-4xl' : 'max-w-lg'

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className={`bg-white rounded-2xl shadow-2xl w-full ${modalWidth} max-h-[92vh] flex flex-col`}>
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <h2 className="font-bold text-gray-900">{editTarget ? 'Edit Template' : 'New Email Template'}</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600"><X size={20} /></button>
        </div>

        <div className={`overflow-y-auto flex-1 ${isCustom ? 'grid grid-cols-[1fr_280px]' : ''}`}>
          {/* Left: form fields */}
          <div className="px-6 py-5 space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Name *</label>
              <input
                type="text"
                value={form.name}
                onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                placeholder="e.g. Weekly Report"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
              <input
                type="text"
                value={form.description}
                onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
                placeholder="Optional description"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Template Type</label>
              <select
                value={form.template_type}
                onChange={e => setForm(f => ({ ...f, template_type: e.target.value as EmailTemplateType }))}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
              >
                <option value="BUILTIN">Built-in (editorial / minimal)</option>
                <option value="CUSTOM_HTML">Custom HTML</option>
                <option value="SENDGRID">SendGrid Dynamic Template</option>
                <option value="MAILCHIMP">Mailchimp Template</option>
                <option value="BREVO">Brevo Template</option>
              </select>
            </div>

            {/* BUILTIN */}
            {form.template_type === 'BUILTIN' && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Built-in layout</label>
                <select
                  value={form.builtin_name}
                  onChange={e => setForm(f => ({ ...f, builtin_name: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                >
                  <option value="editorial">Editorial — magazine style, rich sections</option>
                  <option value="minimal">Minimal — clean, plain, text-focused</option>
                </select>
                <p className="mt-2 text-xs text-gray-400">
                  Built-in layouts are managed by the platform. The agent's generated content is automatically rendered inside the chosen layout — no variables needed.
                </p>
              </div>
            )}

            {/* CUSTOM_HTML */}
            {isCustom && (
              <div className="flex-1">
                <div className="flex items-center justify-between mb-1">
                  <label className="block text-sm font-medium text-gray-700">HTML Content *</label>
                  {!form.html_content && (
                    <button
                      type="button"
                      onClick={() => setForm(f => ({ ...f, html_content: STARTER_TEMPLATE }))}
                      className="inline-flex items-center gap-1 text-xs text-red-600 hover:text-red-700 font-medium"
                    >
                      <Code2 size={12} />
                      Insert starter template
                    </button>
                  )}
                </div>
                <textarea
                  value={form.html_content}
                  onChange={e => setForm(f => ({ ...f, html_content: e.target.value }))}
                  rows={22}
                  spellCheck={false}
                  placeholder={'<!DOCTYPE html>\n<html>\n<body>\n  {{ body }}\n</body>\n</html>'}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg text-xs font-mono focus:outline-none focus:ring-2 focus:ring-red-500 resize-none leading-relaxed"
                />
              </div>
            )}

            {/* Third-party */}
            {isThirdParty && (
              <>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Template ID</label>
                  <input
                    type="text"
                    value={form.external_template_id}
                    onChange={e => setForm(f => ({ ...f, external_template_id: e.target.value }))}
                    placeholder={
                      form.template_type === 'SENDGRID' ? 'd-xxxxxxxxxxxxxxxxxxxx' :
                      form.template_type === 'MAILCHIMP' ? 'template_id or campaign name' :
                      'Template ID in Brevo'
                    }
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">From Email <span className="font-normal text-gray-400">(optional)</span></label>
                  <input
                    type="email"
                    value={(form.external_config as any)?.from_email ?? ''}
                    onChange={e => setForm(f => ({ ...f, external_config: { ...(f.external_config || {}), from_email: e.target.value } }))}
                    placeholder="sender@yourdomain.com"
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
                  />
                  <p className="mt-1 text-xs text-gray-400">Credentials are pulled from the matching integration in your account settings.</p>
                </div>
              </>
            )}
          </div>

          {/* Right: variables reference panel — only for CUSTOM_HTML */}
          {isCustom && (
            <div className="border-l border-gray-100 bg-gray-50 px-5 py-5 overflow-y-auto">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Template Variables</p>

              <div className="space-y-3 mb-5">
                {VARIABLES_REFERENCE.map(v => (
                  <div key={v.variable} className="bg-white rounded-lg border border-gray-200 p-3">
                    <div className="flex items-center gap-1 mb-1">
                      <code className="text-xs font-mono text-red-600 font-semibold">{v.variable}</code>
                      <CopyButton text={v.variable} />
                    </div>
                    <p className="text-xs text-gray-500 leading-relaxed">{v.desc}</p>
                  </div>
                ))}
              </div>

              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">How it works</p>
              <div className="space-y-2 text-xs text-gray-500 leading-relaxed">
                <p>When the agent calls <code className="bg-white border border-gray-200 px-1 rounded font-mono text-gray-700">internal_send_email</code>, it writes the email content. Your template wraps that content automatically.</p>
                <p>Place <code className="bg-white border border-gray-200 px-1 rounded font-mono text-red-600">{`{{ body }}`}</code> exactly where you want the agent's content to appear.</p>
                <p>The template is rendered using <strong>Jinja2</strong>, so you can use any Jinja2 expression:</p>
              </div>

              <div className="mt-3 space-y-2">
                {[
                  ['Conditional block', `{% if subject %}\n<h2>{{ subject }}</h2>\n{% endif %}`],
                  ['Loop', `{% for item in items %}\n<li>{{ item }}</li>\n{% endfor %}`],
                  ['Filter', `{{ body | safe }}`],
                ].map(([label, code]) => (
                  <div key={label} className="bg-white rounded-lg border border-gray-200 p-3">
                    <p className="text-xs font-medium text-gray-600 mb-1">{label}</p>
                    <div className="flex items-start justify-between gap-1">
                      <pre className="text-xs font-mono text-gray-500 whitespace-pre-wrap leading-relaxed">{code}</pre>
                      <CopyButton text={code} />
                    </div>
                  </div>
                ))}
              </div>

              <div className="mt-4 rounded-lg bg-amber-50 border border-amber-200 p-3">
                <p className="text-xs font-semibold text-amber-800 mb-1">Tips</p>
                <ul className="text-xs text-amber-700 space-y-1 list-disc list-inside">
                  <li>Always include <code className="font-mono">{`{{ body }}`}</code> — without it the email content won't show</li>
                  <li>Use inline CSS for best email client compatibility</li>
                  <li>Max width 600px is recommended for email</li>
                  <li>Test in multiple clients before going live</li>
                </ul>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-200">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            onClick={onSave}
            disabled={saving}
            className="px-5 py-2 text-sm font-medium text-white bg-red-600 hover:bg-red-700 rounded-lg disabled:opacity-60 transition-colors"
          >
            {saving ? 'Saving…' : editTarget ? 'Save Changes' : 'Create Template'}
          </button>
        </div>
      </div>
    </div>
  )
}

const EMPTY: CreateEmailTemplatePayload = {
  name: '',
  description: '',
  template_type: 'BUILTIN',
  builtin_name: 'editorial',
  html_content: '',
  external_provider: '',
  external_template_id: '',
  external_config: {},
}

export default function EmailTemplatesPage() {
  const [templates, setTemplates] = useState<EmailTemplate[]>([])
  const [loading, setLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)
  const [editTarget, setEditTarget] = useState<EmailTemplate | null>(null)
  const [form, setForm] = useState<CreateEmailTemplatePayload>(EMPTY)
  const [saving, setSaving] = useState(false)
  const [previewId, setPreviewId] = useState<string | null>(null)

  useEffect(() => { fetchTemplates() }, [])

  const fetchTemplates = async () => {
    try {
      setLoading(true)
      const data = await listEmailTemplates()
      setTemplates(data)
    } catch (e) {
      toast.error('Failed to load email templates')
    } finally {
      setLoading(false)
    }
  }

  const openCreate = () => {
    setEditTarget(null)
    setForm(EMPTY)
    setShowModal(true)
  }

  const openEdit = (t: EmailTemplate) => {
    setEditTarget(t)
    setForm({
      name: t.name,
      description: t.description ?? '',
      template_type: t.template_type,
      builtin_name: t.builtin_name ?? 'editorial',
      html_content: t.html_content ?? '',
      external_provider: t.external_provider ?? '',
      external_template_id: t.external_template_id ?? '',
      external_config: t.external_config ?? {},
    })
    setShowModal(true)
  }

  const handleSave = async () => {
    if (!form.name.trim()) { toast.error('Name is required'); return }
    setSaving(true)
    try {
      const payload: CreateEmailTemplatePayload = {
        name: form.name.trim(),
        description: form.description || undefined,
        template_type: form.template_type,
        builtin_name: form.template_type === 'BUILTIN' ? form.builtin_name : undefined,
        html_content: form.template_type === 'CUSTOM_HTML' ? form.html_content : undefined,
        external_provider: ['SENDGRID', 'MAILCHIMP', 'BREVO'].includes(form.template_type) ? form.external_provider : undefined,
        external_template_id: ['SENDGRID', 'MAILCHIMP', 'BREVO'].includes(form.template_type) ? form.external_template_id : undefined,
        external_config: ['SENDGRID', 'MAILCHIMP', 'BREVO'].includes(form.template_type) ? form.external_config : undefined,
      }

      if (editTarget) {
        await updateEmailTemplate(editTarget.id, payload)
        toast.success('Template updated')
      } else {
        await createEmailTemplate(payload)
        toast.success('Template created')
      }
      setShowModal(false)
      fetchTemplates()
    } catch (e: any) {
      toast.error(e.message || 'Failed to save template')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async (id: string, name: string) => {
    if (!confirm(`Delete "${name}"?`)) return
    try {
      await deleteEmailTemplate(id)
      toast.success('Template deleted')
      fetchTemplates()
    } catch (e) {
      toast.error('Failed to delete template')
    }
  }

  const isThirdParty = ['SENDGRID', 'MAILCHIMP', 'BREVO'].includes(form.template_type)

  return (
    <div className="dashboard-resource-page min-h-screen">
      <div className="max-w-5xl mx-auto px-4 md:px-6 py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-gray-900 tracking-tight">Email Templates</h1>
            <p className="text-gray-500 mt-1 text-sm">
              Manage reusable templates for agent emails. Assign a template to an agent from its edit page.
            </p>
          </div>
          <button
            onClick={openCreate}
            className="inline-flex items-center gap-2 px-4 py-2 bg-red-600 text-white text-sm font-medium rounded-lg hover:bg-red-700 transition-colors"
          >
            <Plus size={18} />
            New Template
          </button>
        </div>

        {/* List */}
        {loading ? (
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="bg-white rounded-xl border border-gray-200 p-5 animate-pulse">
                <div className="h-4 bg-gray-200 rounded w-40 mb-2" />
                <div className="h-3 bg-gray-100 rounded w-64" />
              </div>
            ))}
          </div>
        ) : templates.length === 0 ? (
          <div className="text-center py-20">
            <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Mail className="w-8 h-8 text-red-500" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">No email templates yet</h3>
            <p className="text-gray-500 text-sm mb-6">Create a template to assign to your agents</p>
            <button onClick={openCreate} className="inline-flex items-center gap-2 px-5 py-2 bg-red-600 text-white text-sm font-medium rounded-lg hover:bg-red-700 transition-colors">
              <Plus size={16} /> New Template
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            {templates.map((t) => (
              <div key={t.id} className="bg-white rounded-xl border border-gray-200 p-5 hover:shadow-sm transition-shadow">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-semibold text-gray-900">{t.name}</span>
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${TYPE_COLORS[t.template_type]}`}>
                        {TYPE_LABELS[t.template_type]}
                      </span>
                    </div>
                    {t.description && <p className="text-sm text-gray-500 mb-2">{t.description}</p>}
                    <div className="text-xs text-gray-400">
                      {t.template_type === 'BUILTIN' && `Layout: ${t.builtin_name || 'editorial'}`}
                      {t.template_type === 'CUSTOM_HTML' && 'Custom HTML layout'}
                      {['SENDGRID', 'MAILCHIMP', 'BREVO'].includes(t.template_type) && (
                        <span>Template ID: <code className="bg-gray-100 px-1 rounded">{t.external_template_id || '—'}</code></span>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 flex-shrink-0">
                    {t.preview_html && (
                      <button
                        onClick={() => setPreviewId(previewId === t.id ? null : t.id)}
                        className="px-3 py-1.5 text-xs font-medium text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50"
                      >
                        Preview
                      </button>
                    )}
                    <button onClick={() => openEdit(t)} className="p-1.5 text-gray-400 hover:text-gray-700 rounded-lg hover:bg-gray-100 transition-colors">
                      <Edit2 size={15} />
                    </button>
                    <button onClick={() => handleDelete(t.id, t.name)} className="p-1.5 text-gray-400 hover:text-red-600 rounded-lg hover:bg-red-50 transition-colors">
                      <Trash2 size={15} />
                    </button>
                  </div>
                </div>
                {previewId === t.id && t.preview_html && (
                  <div className="mt-4 border border-gray-200 rounded-lg overflow-hidden">
                    <iframe
                      srcDoc={t.preview_html}
                      className="w-full h-80"
                      sandbox="allow-same-origin"
                      title="Template preview"
                    />
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Create / Edit Modal */}
      {showModal && (
        <TemplateModal
          editTarget={editTarget}
          form={form}
          setForm={setForm}
          saving={saving}
          onSave={handleSave}
          onClose={() => setShowModal(false)}
        />
      )}
    </div>
  )
}
